graph LR
  U1 --> U2 --> U3 --> U4 --> U5 --> U6 --> U7 --> U8
  U1[U1: Estadística Descriptiva]
  U2[U2: Probabilidad y Combinatoria]
  U3[U3: Variables Aleatorias Discretas]
  U4[U4: Distribuciones Conjuntas]
  U5[U5: Variables Aleatorias Continuas]
  U6[U6: Modelado y Simulación]
  U7[U7: Inferencia y Estimación]
  U8[U8: Proyecto Integrador]
  U2 -.Teorema de Bayes y Probabilidad Condicional.-> U3
  U3 -.PMF de Variables Aleatorias Discretas.-> U4
  U5 -.Distribuciones Continuas y su CDF.-> U6
  U2 -.Simulación Monte Carlo.-> U6
  U5 -.Distribuciones Muestrales: Chi-cuadrada, t-Student y F.-> U7
  U1 -.Estadística Descriptiva y Medidas de Tendencia Central.-> U7
  U7 -.Pruebas de Hipótesis e Inferencia Estadística.-> U8
  U4 -.PCA y Whitening Gaussiano.-> U8